### PR TITLE
Index Parents

### PR DESCRIPTION
**Pull request by rushtong**
Addresses https://broadinstitute.atlassian.net/browse/GAWB-1642

Add all parent nodes (with order) to each term.
Significant refactoring of `IndexOntologyService` and a new test to cover ES-based features.

## Deployment Note
This will require a deletion of the current index due to mapping changes.

# Testing
Your user needs to be an Admin to make ontology file updates. Please touch base with @rushtong to make that happen. 

## Testing against the dev index:
These endpoints can be tested against the current endpoint with this branch (but not worked on for this PR):
* GET /ontology
* GET /ontology/file
* GET /ontology/types

Not currently testable (and not worked on for this PR): 
* PUT /ontology

## Testing against custom index:
For testing `POST /ontology` (this PR) you will need a separate file storage bucket and ES index. I have that set up for my local testing, so you'll need to change the bucket and ES sections of `config/consent.conf` to look like this (note the `ontology-local` changes:
```
storeOntology:
  bucketSubdirectory: ontology-local
  configurationFileName: /configuration
elasticSearch:
  clusterName: consent-elasticsearch
  servers:
    - consent-elasticsearch1.dsde-dev.broadinstitute.org
    - consent-elasticsearch2.dsde-dev.broadinstitute.org
    - consent-elasticsearch3.dsde-dev.broadinstitute.org
  indexName: ontology-local
```
Alternatively, you can log into google cloud console and set up a new bucket if you wish: https://console.cloud.google.com/storage/browser/broad-dsde-dev-consent/ Just make sure to properly reference your new bucket (and to be safe, a similar ES `indexName`) in your config.

### Ontology Files for Testing:
* Both files can be found here: https://github.com/broadinstitute/consent-ontology/tree/develop/src/test/resources
* data-use.owl
* diseases.owl

Go to the swagger page and test each of the "Ontology" swagger endpoints.
After uploading ontology files (see above), you can examine the contents of the index with these example ES queries. Feel free to explore. Most nodes (not all, top level nodes have no parents) should have a `parents` section with an array of parents, each one indicating its distance from the node. Most (if not all) deprecated terms do not have parent nodes.

* http://consent-elasticsearch1.dsde-dev.broadinstitute.org:9200/ontology-local/_search?q=ontology=Disease
* http://consent-elasticsearch1.dsde-dev.broadinstitute.org:9200/ontology-local/_search?q=ontology:Organization
* http://consent-elasticsearch1.dsde-dev.broadinstitute.org:9200/ontology-local/_search?q=Cancer&size=100
* http://consent-elasticsearch1.dsde-dev.broadinstitute.org:9200/ontology-local/_search?q=Apnea
* http://consent-elasticsearch1.dsde-dev.broadinstitute.org:9200/ontology-local/_count?q=ontology:Disease
* http://consent-elasticsearch1.dsde-dev.broadinstitute.org:9200/ontology-local/_count?q=ontology:Organization

---
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [x] **TL** sign off
- [x] **LR** sign off
- [x] **Product Owner** sign off
- [x] **Assign to submitter** to finalize
- [x] **Submitter**: Verify all tests go green, including CI tests
- [x] **Submitter**: Squash commits and merge to develop
- [x] **Submitter**: Delete branch after merge
- [x] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [x] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [x] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [x] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Review by skwalker — COMMENTED** [review]
This looks good to me, my only question is about the multiple parent situation.

**Review by davidangb — DISMISSED** [review]
Some changes requested inline; I haven't pulled and tested.

Depending on how it goes inside orchestration when publishing datasets to Library, we may want to change what gets indexed here in consent. Currently, we index label/id/synonyms/description for the leaf node, and id/distance for each parent. We may need to change so that we're also indexing label and possibly synonyms/description for each parent as well (this would require changes in ontology too).

**Review by davidangb — COMMENTED** [review]
latest changes look good; as discussed, remove the deletions before indexing new nodes.

**Review by davidangb — APPROVED** [review]
👍 lgtm! (did not test)

**Pull request merged**
