### PR TITLE
[DUOS-2189][risk=no] Remove nih certification file from schema

### PR DESCRIPTION
**Pull request by rushtong**
## Addresses
Partially addresses https://broadworkbench.atlassian.net/browse/DUOS-2189

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by quazi-h — APPROVED** [review]
Removal of NIH certification from the backend here looks good to me.

**Comment by JVThomas** [comment]
Quick question: Is the `nihInstitutionalCertificationFileName` to be removed completely from the schema? The schema endpoint still has it in its response because it reads the schema off of `dataset-registration-schema_v1.json`, which still has the key listed.

**Comment by rushtong** [comment]
> Quick question: Is the `nihInstitutionalCertificationFileName` to be removed completely from the schema? The schema endpoint still has it in its response because it reads the schema off of `dataset-registration-schema_v1.json`, which still has the key listed.

That should be gone ... looks like I missed it in the chaos ... will address.

**Review by otchet-broad — APPROVED** [review]
Model and resource changes all look good.

**Pull request merged**
