### PR TITLE
[BTRX-419][risk=no] Align templates with FC

### PR DESCRIPTION
**Pull request by rushtong**
## Addresses
https://broadinstitute.atlassian.net/browse/BTRX-419
See https://github.com/broadinstitute/firecloud-orchestration for what we are aligning to.

### CODE REVIEW

**Review by LeoForconesi — APPROVED** [review]
This looks good to me!.
Is there any possibility that we include Swagger UI update reminder between the checkboxes? That have helped me to remember and review it multiple times. Or maybe in the Contributing.md file? It's just my humble opinion :)

**Comment by rushtong** [comment]
@LeoForconesi - It is in the contributing, but I can add a checkbox for it as well.

**Comment by rushtong** [comment]
@LeoForconesi - Feedback added. Also, see https://github.com/DataBiosphere/consent-ontology/pull/106 for the same thing for ontology. Thank you!

**Comment by LeoForconesi** [comment]
You're right, thanks for adding it as a checkbox, it's really useful there. :+1:

**Pull request merged**
