### PR TITLE
[DUOS-376][risk=no] User -> AuthUser

### PR DESCRIPTION
**Pull request by rushtong**
## Addresses
Partially addresses https://broadinstitute.atlassian.net/browse/DUOS-376

## Changes
Isolated class rename so that we can rename `DACUser` -> `User` in future multi-DAC work.

### CODE REVIEW

**Review by MatthewBemis — APPROVED** [review]
Despite my complete lack of context of this application, the changes are clear and look good to me. :+1:

**Comment by rushtong** [comment]
Thank you @MatthewBemis !

**Review by danxmoran — APPROVED** [review]

**Review by thathert — APPROVED** [review]
LGTM

**Comment by rushtong** [comment]
Thanks all!

**Pull request merged**
