### PR TITLE
[DUOS-1770][risk=no] Restrict manage v2 DARs to signing officials only

### PR DESCRIPTION
**Pull request by rushtong**
## Addresses
https://broadworkbench.atlassian.net/browse/DUOS-1770

All usages of this endpoint have been removed aside from the SO console. Restrict this to the SO role and clean up unused code.

Removed an automation test that tried to hit this endpoint as an admin. These tests will be re-written in Java in https://broadworkbench.atlassian.net/browse/DUOS-1684 so we're not adding additional tests for the updated methods.

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by shaemarks** [comment]
Side note: I think we should be able to remove the SO usage of this endpoint on the frontend as well. The endpoint is used on the `SigningOfficialConsole` component, with the `/signing_official_console` path, which we don't directly link to. With the new nav bar, we send users to `/signing_official_console/researchers` (`SigningOfficialResearcher` component) and `/signing_official_console/dar_requests` (`SigningOfficialDarRequests` component), neither of which call `DAR.getDataAccessManageV2`

**Comment by rushtong** [comment]
> Side note: I think we should be able to remove the SO usage of this endpoint on the frontend as well. The endpoint is used on the `SigningOfficialConsole` component, with the `/signing_official_console` path, which we don't directly link to. With the new nav bar, we send users to `/signing_official_console/researchers` (`SigningOfficialResearcher` component) and `/signing_official_console/dar_requests` (`SigningOfficialDarRequests` component), neither of which call `DAR.getDataAccessManageV2`

`SigningOfficialConsole` currently calls `DAR.getDataAccessManageV2` ... when we end up removing that, we can finally remove the consent API altogether.

**Comment by shaemarks** [comment]
> `SigningOfficialConsole` currently calls `DAR.getDataAccessManageV2` ... when we end up removing that, we can finally remove the consent API altogether.

Yeah, I was just mentioning that `SigningOfficialConsole` should be ready for removal since we no longer send users to it. As far as I know, we don't have a ticket to remove it yet

**Comment by rushtong** [comment]
> Yeah, I was just mentioning that `SigningOfficialConsole` should be ready for removal since we no longer send users to it. As far as I know, we don't have a ticket to remove it yet

Aha, that is very true. I'll file a ticket for that and once that's finished, I'll update this PR.

**Review by shaemarks — APPROVED** [review]
Looks good to me! Signing official role is still supported, and other roles are deprecated for this endpoint

**Review by connorlbark — APPROVED** [review]
👍

**Pull request merged**
