### PR TITLE
[DUOS-1127][risk=no] Add researcher info with properties to the dar manage response

### PR DESCRIPTION
**Pull request by rushtong**
## Addresses
Back end support for changes related to https://broadworkbench.atlassian.net/browse/DUOS-1127

## Changes
* Add the DAR's researcher (user object) to the DAR Manage object
* Clean up api documentation

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/DataBiosphere/consent/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/DataBiosphere/consent/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing
- [ ] I've updated Swagger to reflect any API changes

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by JVThomas** [comment]
Since this is the Manage endpoint, can we simplify the Researcher model being added to the response? The UI only needs the  id for the Researcher Review redirect and the status for icon/status rendering. This way the response can be much smaller, you can just skip over processing the researcher properties, and there wouldn't be side effects with other components (Only NewChairConsole and AdminManageAccess use it, and NewChair doesn't use the Researcher properties).

Not sure if it's a Java thing, but I know Rails and Express promote using custom serializers to trim off extraneous data on models if needed (key takeaway is the trimming, not the serializer).

**Comment by rushtong** [comment]
@JVThomas 
> can we simplify the Researcher model being added to the response?

Absolutely, I will make this cleaner.

**Comment by rushtong** [comment]
@JVThomas This is ready for re-review.

**Review by JVThomas — APPROVED** [review]
Code looks good! This will really help out with the UI counterpart!

**Pull request merged**
