### PR TITLE
[DUOS-1583][risk=no] Another maven compiler config

### PR DESCRIPTION
**Pull request by rushtong**
## Addresses
https://broadworkbench.atlassian.net/browse/DUOS-1583

I missed this config in the initial migration

See also: https://github.com/DataBiosphere/consent-ontology/pull/669

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by quazi-h — APPROVED** [review]
Changes look straightforward.

**Comment by shaemarks** [comment]
I might have found another config that should be changed. I tested out the changes in this PR by using the new text block feature (not needing to use escape characters by wrapping string in """) and running `mvn clean test package`. Running as is, I got a compilation failure. After changing the shown configuration to `17` in `pom.xl`, I got build success with this command and was able to run the tests.

BEFORE:
Screenshot (97)

AFTER:
Screenshot (96)

**Comment by rushtong** [comment]
> I might have found another config that should be changed. I tested out the changes in this PR by using the new text block feature (not needing to use escape characters by wrapping string in """) and running `mvn clean test package`. Running as is, I got a compilation failure. After changing the shown configuration to `17` in `pom.xl`, I got build success with this command and was able to run the tests.

Nice catch @shaemarks - I'm updating that and the ontology PR with this as well.

**Review by shaemarks — APPROVED** [review]
Tested locally with `mvn clean test package` and got build success with a java 17 feature

**Pull request merged**
