### PR TITLE
[DUOS-2156][risk=no] Update Sentry Logging

### PR DESCRIPTION
**Pull request by rushtong**
## Addresses
https://broadworkbench.atlassian.net/browse/DUOS-2156

Requires https://github.com/broadinstitute/terra-helmfile/pull/3483

This PR: 
* Replaces `org.dhatim` with a direct `sentry` implementation
* Centralizes resource level logging to a common interface

This PR does not comprehensively replace logging across the system, that will be done in future PRs. This is intended to get the transition started.

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by quazi-h — COMMENTED** [review]
Is it possible to test the sentry logging with a locally running instance of consent?
I spun up an instance with the updated sentryDSN value in my docker-compose file (as we did in the recent ontology sentry ticket). I then attempted to use a few of the api endpoints with invalid inputs to create an error. When checking the firecloud-alpha sentry instance, I keep seeing a GoogleJsonResponseException but I don't think it was related to my call. Looking through the stack trace I didn't see anything related to DUOS or consent. Am I looking in the correct place and testing this correctly?

**Comment by rushtong** [comment]
> Is it possible to test the sentry logging with a locally running instance of consent?
> I spun up an instance with the updated sentryDSN value in my docker-compose file (as we did in the recent ontology sentry ticket). I then attempted to use a few of the api endpoints with invalid inputs to create an error. When checking the firecloud-alpha sentry instance, I keep seeing a GoogleJsonResponseException but I don't think it was related to my call. Looking through the stack trace I didn't see anything related to DUOS or consent. Am I looking in the correct place and testing this correctly?

I didn't add a specific endpoint to test this like I did for https://github.com/DataBiosphere/consent-ontology/pull/698
Instead, you could modify an easy endpoint, like the version api, to log an exception. I added one line to `VersionResource`:
```
    public Response content() {
        Version version = new Version(getGitProperties());
--->    logException(new BadRequestException("Testing Bad Request Exception"));
        return Response.ok().entity(version).build();
    }
```
and was able to see the log in both the console:
```
consent  | ERROR [2022-10-24 13:25:58,471] org.broadinstitute.consent.http.resources.VersionResource: Testing Bad Request Exception
consent  | 192.168.96.4 - - [24/Oct/2022:13:25:58 +0000] "GET /version HTTP/1.1" 200 41 "https://local.broadinstitute.org:27443/" 
```
and in Sentry:
Screen Shot 2022-10-24 at 9 26 46 AM

**Review by quazi-h — APPROVED** [review]
Sentry logging is working correctly for me when I tried testing with your recommendations. Thanks for pointing me in the right direction!

**Review by JVThomas — APPROVED** [review]
Tested locally, confirmed logging shows up on Sentry. Just need to resolve merge conflicts

**Comment by rushtong** [comment]
I accidentally merged changes for a different story to this PR ... will revert from https://github.com/DataBiosphere/consent/pull/1782/commits/1cf900c5bb253a649b2ef0857ea2ee1901817b40 onward.

**Pull request merged**
