### PR TITLE
DUOS-945[risk=no]Add DAC UID to the table

### PR DESCRIPTION
**Pull request by raejohanek**
## Addresses:
https://broadworkbench.atlassian.net/browse/DUOS-945

## Scope:
-add DAC UID to header on DAR and DAC
-add DAC UID values to body of table
-create method on interface that given the name will generate the UID if there is one
-if the DAC name contains no numbers, there will be no UID displayed

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/DataBiosphere/consent/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/DataBiosphere/consent/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing
- [ ] I've updated Swagger to reflect any API changes

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by rushtong** [comment]
This branch has code that has already been merged in https://github.com/DataBiosphere/consent/pull/904. Update your develop branch, then merge from develop into this one so the base of this branch is up to date.

**Review by rushtong — CHANGES_REQUESTED** [review]
Please revert all changes to `DecisionMetrics.java` - they are unrelated to the scope of this PR.

**Comment by raejohanek** [comment]
> Please revert all changes to `DecisionMetrics.java` - they are unrelated to the scope of this PR.

The only changes to this file are formatting and the addition of getDacUID(string name) which is for this PR.

**Comment by rushtong** [comment]
@raejohanek 

> The only changes to this file are formatting and the addition of getDacUID(string name) which is for this PR.

Yes, the formatting changes in `DecisionMetrics` is what I was requesting that you revert, not your functional code changes. We try to keep PRs limited in scope to the what is required to complete the story. The formatting changes had no relation to the requirements for the story and no changes are required to that file for the functionality to work as you intended, hence the PR feedback. I'll 👍🏽  this as is but do try to keep the scope of changes small and limited. Thank you!

**Review by rushtong — APPROVED** [review]
👍🏽

**Pull request merged**
