### PR TITLE
[DUOS-1808][risk=no] Allow for admins to delete existing elections and votes for a dar

### PR DESCRIPTION
**Pull request by rushtong**
## Addresses
https://broadworkbench.atlassian.net/browse/DUOS-1808

Minor updates to the delete DAR api so that admins can delete existing elections and votes associated to the DAR.

I've tested this with a local copy of both dev and staging databases on all of the problematic reference ids.

Example query to test before and after cases:
```
select reference_id, count(*) 
from data_access_request
group by reference_id
having count(*) > 1
```

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by JVThomas — APPROVED** [review]
Only one nitpick: Can you update the api description for the DAR delete endpoint so that it's clear that associated Votes , Elections, and any other associated models are removed when an Admin uses it?

**Comment by rushtong** [comment]
> Only one nitpick: Can you update the api description for the DAR delete endpoint so that it's clear that associated Votes and Elections are removed when an Admin uses it?

Nice catch, will do!

**Comment by rushtong** [comment]
@JVThomas - updated, PTAL, and thank you!

**Review by shaemarks — APPROVED** [review]
Changes and tests look good to me!

**Review by JVThomas — APPROVED** [review]
Code looks good to go

**Pull request merged**
