### PR TITLE
[DUOS-2474][risk=no] Add application hooks for re/indexing a dataset

### PR DESCRIPTION
**Pull request by fboulnois**
### Addresses

https://broadworkbench.atlassian.net/browse/DUOS-2474

### Summary

Update index when creating or updating dataset or dar.

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by kaitlynoflaherty — APPROVED** [review]
👍 looks good!

**Review by rushtong — APPROVED** [review]
Nice work, very efficient, thank you!

**Review by rushtong — APPROVED** [review]
Looks good!

**Review by kaitlynoflaherty — APPROVED** [review]
👍!

**Pull request merged**
