### PR TITLE
Broadinstitute -> DataBiosphere changes

### PR DESCRIPTION
**Pull request by rushtong**
Addresses https://broadinstitute.atlassian.net/browse/GAWB-3024
Updates for the migration from broadinstitute -> DataBiosphere github/travis orgs. 

See also: 
* https://github.com/DataBiosphere/consent-ui/pull/163
* https://github.com/DataBiosphere/consent-ontology/pull/89

---

- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [x] **TL** sign off
- [x] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Review by davidangb — COMMENTED** [review]
add the coverage badge too?

**Review by aednichols — COMMENTED** [review]
Looks fine pending David's comments; will thumb then. Travis is verifiably back.

**Comment by rushtong** [comment]
@davidangb - The links to coveralls are incorrect. The coveralls builds are only relevant for repos in broadinstitute, not in DataBiosphere, so linking to those doesn't make sense any more. Also, we don't have a DataBiosphere coveralls account set up. Looking at the Leonardo coveralls badge, that points to older, pre-move builds. Will ponder potential solutions.

**Review by davidangb — APPROVED** [review]
:+1: okay, no worries on coveralls badge. Approving, and don't hold up merging, but: how does one access coverage stats now?

**Review by aednichols — APPROVED** [review]
👍

**Pull request merged**
