### PR TITLE
[DUOS-446][risk=no] Remove unused DAA code

### PR DESCRIPTION
**Pull request by rushtong**
## Addresses
API side of https://broadinstitute.atlassian.net/browse/DUOS-446
See also: https://github.com/DataBiosphere/duos-ui/pull/614

## Changes
Pure code removal. We no longer upload or download a DAA for the user, that code has been removed from the UI for some time.

---

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [x] I've followed [the instructions](https://github.com/DataBiosphere/consent/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [x] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [x] I've updated the [FISMA documentation](https://github.com/DataBiosphere/consent/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing
- [x] I've updated Swagger to reflect any API changes

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [x] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by lindojong** [comment]
Although we no longer upload/download DAAs for users, are we going to continue to store legacy ones in the research property table?

**Comment by rushtong** [comment]
@lindojong 
RE:
> Although we no longer upload/download DAAs for users, are we going to continue to store legacy ones in the research property table?

No, we should not. I see that there are `ResearcherFields` that I missed. We were *also* storing them as part of the DAR which is what I was focused on. Will update `ResearcherFields` too.

**Comment by lindojong** [comment]
Other than that, there's also some DarConstants for DAAs that are being used inside `DataAccessParser`. After that, LGTM!

**Comment by rushtong** [comment]
@lindojong - I don't see any references to the DAA fields in DataAccessParser, just standard DarConstants that we should be looking at.

**Comment by lindojong** [comment]
line 257:
`case DarConstants.DATA_ACCESS_AGREEMENT: {
                    Boolean existDataAccessAgreement = (StringUtils.isNotEmpty(dar.getString(DarConstants.DATA_ACCESS_AGREEMENT_URL)) &&
                            StringUtils.isNotEmpty(dar.getString(DarConstants.DATA_ACCESS_AGREEMENT_NAME)));
                    field.setValue(getYesOrNoValue(existDataAccessAgreement));
                    break;
                }`

It looks like this part just checks if a DAA exists

**Comment by rushtong** [comment]
Aha, thank you. Even more code to delete.

**Comment by rushtong** [comment]
Fixed!

**Review by lindojong — APPROVED** [review]

**Pull request merged**
