### PR TITLE
[DUOS-1631][risk=no] Send Submitted For Review Email For DAR Collections

### PR DESCRIPTION
**Pull request by rushtong**
## Addresses
https://broadworkbench.atlassian.net/browse/DUOS-1631

## Changes
Updated the logic around sending emails for every DAR in a collection. Instead, we send a single message about the collection to each user in the DAC. 

## Testing
* Set up some number of test users in a DAC
* Assign some datasets to that DAC, or use a DAC that already has datasets
* Set your local mail configuration in consent to true: `activateEmailNotifications: true`
* As a researcher user, create a DAR against those datasets. **Important** that there be more than one so there will be multiple DARs in the collection
* As an admin or chair, visit the new chair console page and create an election for the submitted collection. **Important** that you visit the new console page - the old one only creates one election per DAR.
* Check that your DAC user received exactly 1 email for the submitted collection. Previously, you would have received N emails, one per DAR in the collection.

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by rushtong** [comment]
Seeing some test flakiness. These pass locally:
```
Error:  Failures: 
Error:    DacDAOTest.testAddDacChair:160 expected:<null> but was:<11>
Error:    DacDAOTest.testAddDacMember:147 expected:<null> but was:<15>
```
Subsequent run failure:
```
Error:  Failures: 
Error:    DacDAOTest.testAddDacMember:147 expected:<null> but was:<15>
```

**Comment by rushtong** [comment]
Increased randomness of dar code to get past this flaky error:
```
Error:  Tests run: 20, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.046 s <<< FAILURE! - in org.broadinstitute.consent.http.db.DataAccessRequestDAOTest
Error:  testFindByReferenceIds(org.broadinstitute.consent.http.db.DataAccessRequestDAOTest)  Time elapsed: 0.082 s  <<< ERROR!
org.jdbi.v3.core.statement.UnableToExecuteStatementException: 
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "dar_collection_dar_code_key"
  Detail: Key (dar_code)=(DAR-500) already exists. [statement:"/* DarCollectionDAO.insertDarCollection */ INSERT INTO dar_collection  (dar_code, create_user_id, create_date)  VALUES (:darCode, :createUserId, :createDate)", arguments:{positional:{0:DAR-500,1:22,2:Thu Apr 07 18:30:44 UTC 2022}, named:{createUserId:22,darCode:DAR-500,createDate:Thu Apr 07 18:30:44 UTC 2022}, finder:[]}]
	at org.broadinstitute.consent.http.db.DataAccessRequestDAOTest.testFindByReferenceIds(DataAccessRequestDAOTest.java:113)
Caused by: org.postgresql.util.PSQLException: 
ERROR: duplicate key value violates unique constraint "dar_collection_dar_code_key"
  Detail: Key (dar_code)=(DAR-500) already exists.
	at org.broadinstitute.consent.http.db.DataAccessRequestDAOTest.testFindByReferenceIds(DataAccessRequestDAOTest.java:113)
```

**Review by shaemarks — APPROVED** [review]
Code looks good, and for my test DAC, each member received a single email for a collection with multiple datasets/dars.

Note: As an admin, I received a separate email for each dataset/dar telling me to create the election for it, but I believe this is out of scope for this ticket.

**Comment by rushtong** [comment]
@shaemarks 
> Note: As an admin, I received a separate email for each dataset/dar telling me to create the election for it, but I believe this is out of scope for this ticket.

That is correct - this story is meant to cover the emails sent out when an election is created for a DAR Collection. The admin emails are being sent when a DAR Collection is being submitted by the researcher is an earlier event in the workflow. We do need to tackle that as well - I don't think we have a ticket for it, so will do that now.

**Review by quazi-h — APPROVED** [review]
Changes to only send one email per collection instead of one per unique dar, dataset look good to me. Tests look good as well.

**Pull request merged**
