### PR TITLE
GAWB-2782: Index Parent Labels

### PR DESCRIPTION
**Pull request by rushtong**
Add the label of the parents when pushing terms to elastic search.

Supports https://broadinstitute.atlassian.net/browse/GAWB-2782

## Testing:
* Spin up
* Log in as an admin: 
* Download this ontology file: https://console.cloud.google.com/storage/browser/broad-dsde-dev-consent/ontology-local/disease/?project=broad-dsde-dev
* Use `{ "ontology_file": { "prefix": "DOID", "type": "Disease" } }` as the metadata
* And upload via your local swagger.

After uploading, you should be able to query one of the ES hosts (see your local config for those) with this query url: `http://<insert es host here>:9200/ontology-local/_search?q=cancer`

Parents should now have a label value:
```
"parents": [
{
"id": "http://purl.obolibrary.org/obo/DOID_8564",
"label": "lip cancer",
"order": 1
}...
```

- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [x] **TL** sign off
- [x] **LR** sign off
- [x] **Product Owner** sign off
- [x] **Assign to submitter** to finalize
- [x] **Submitter**: Verify all tests go green, including CI tests
- [x] **Submitter**: Squash commits and merge to develop
- [x] **Submitter**: Delete branch after merge
- [x] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [x] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [x] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [x] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by davidangb** [comment]
by adding these parent labels to each term, the parent labels become fulltext searchable (unless we explicitly tell it otherwise). Are there any APIs that use search that could be adversely affected?

**Comment by rushtong** [comment]
@davidangb - Orchestration is the only service that uses this API - it's not in use by any other services that I'm aware of. ORSP has not migrated to using this yet, but that is on my list.

**Comment by aednichols** [comment]
I'm encountering the following build error running `mvn clean test package`, it's one of the files that changed
```
IndexOntologyServiceTest.java:[74,13] org.broadinstitute.consent.http.models.ontology.Term.Parent is not public in org.broadinstitute.consent.http.models.ontology.Term; cannot be accessed from outside package
```

**Review by davidangb — APPROVED** [review]
:+1: working for me, code looks good!

**Comment by davidangb** [comment]
@aednichols make sure you have the third commit on this PR :)

**Review by aednichols — APPROVED** [review]
Tested & works.

**Pull request merged**
