### PR TITLE
[DUOS-2951][risk=no] Post DAA API

### PR DESCRIPTION
**Pull request by rushtong**
### Addresses
https://broadworkbench.atlassian.net/browse/DUOS-2951

### Summary
* Requires https://github.com/DataBiosphere/consent/pull/2256
* Adds a new resource class for DAAs along with api documentation

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by fboulnois — APPROVED** [review]
looks good 👍

**Review by aarohinadkarni — COMMENTED** [review]
manually tested on the Swagger, looks good to me besides the test failures in DaaResourceTest 👍

**Comment by rushtong** [comment]
> manually tested on the Swagger, looks good to me besides the test failures in DaaResourceTest

There are some actions that don't seem to be executing ... I didn't see the failing `DaaResourceTest` here, but it is failing locally

**Comment by rushtong** [comment]
> There are some actions that don't seem to be executing ... I didn't see the failing DaaResourceTest here, but it is failing locally

Ok, that's due to the base branch not being develop. Once https://github.com/DataBiosphere/consent/pull/2256 is finalized, I'll rebase this and clean up any test failures

**Review by aarohinadkarni — APPROVED** [review]
looks good, thank you! 👍

**Pull request merged**
