### PR TITLE
[DUOS-1130][risk=no] Fix dataset delete by id/user

### PR DESCRIPTION
**Pull request by rushtong**
## Addresses
https://broadworkbench.atlassian.net/browse/DUOS-1130

Clean up the delete by id/user code.

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/DataBiosphere/consent/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/DataBiosphere/consent/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing
- [ ] I've updated Swagger to reflect any API changes

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by raejohanek — CHANGES_REQUESTED** [review]
when I test this out I still get the 500 failed to rollback error, is that bc this needs the 1178 PR too?

**Comment by rushtong** [comment]
That can't happen, there's no rollback code in this PR. Remember to do a clean maven build.

**Review by JVThomas — APPROVED** [review]
Can confirm successful deletion of dataset and dataset properties with Swagger and Postico (local deletion).

**Comment by JVThomas** [comment]
Would also like to add that the ```deleteDataset``` function is called on the exception handler for ```createDataset```. Could the old implementation with failed CREATE requests be the reason why impartial datasets exist in the database?

**Comment by rushtong** [comment]
> Would also like to add that the deleteDataset function is called on the exception handler for createDataset. Could the old implementation be the reason why impartial datasets persisted?

It could be ... I haven't gotten to testing that specific error yet. Need to get some of these other bugs fixed before I can replicate the issue in https://broadworkbench.atlassian.net/browse/DUOS-1177

**Review by raejohanek — APPROVED** [review]
tested locally- deletes dataset, dataset properties, and adds delete to dataset audit

**Pull request merged**
