### PR TITLE
[DUOS-1358][risk=no] Fix automation test

### PR DESCRIPTION
**Pull request by rushtong**
## Addresses
https://broadworkbench.atlassian.net/browse/DUOS-1358

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by raejohanek — APPROVED** [review]
test and doc deletions look good/correspond with code already deleted

**Comment by rushtong** [comment]
@raejohanek Thank you! After re-reviewing myself, I made a few more refactoring changes to clean up the code a little more. Will re-request a review.

**Review by raejohanek — APPROVED** [review]
Still 👍 but  just curious - what is the meaning of the 'chains' folder? Also, the scenarios folder? the others (models, services, and requests) seem straightforward

**Comment by rushtong** [comment]
> what is the meaning of the 'chains' folder? Also, the scenarios folder? the others (models, services, and requests) seem straightforward

@raejohanek - Let's cover this in a meeting since we all need to be up to speed on automation tests

**Pull request merged**
